### ISSUE TITLE
Client > eth0 > TorBox > wlan0 > Internet  | Please advise how to ssh to TorBox over ethernet from the first start

### ISSUE THREAD

**Issue by airgap0** [radio24/TorBox#101]
A fresh install of TorBox can not be configured over eth0. For a client without any WLAN capability it seems impossible to set up TorBox via ethernet from the very beginning. It might as well be that I overlooked something, so I ask for your kind understanding.

**Comment by airgap0** [comment]
First try with 054. Here my experience described step by step:
D/L torbox054
Check SHA > pass
Balena Etcher > 16 GB Sandisk
Raspberry 3B 1.2 Interfaces: ETH0 und WLAN0
WLAN torbox054 connect
SSH from Laptop Win11 to Torbox
LAN > Torbox negative 192.168.43.1 no DHCP from Torbox (no route to host)
WIFI > Torbox connect to 192.168.42.1 connected
close/open SSH after ssh-keygen as per instruction
Ethernet cable reconnected (physically) and trying to SSH 192.68.43.1
Connection timeout with Putty via Ethernet
Continueing with SSH over WLAN (192.168.42.1)
Select WLAN0 as source of Internet
WLAN from Torbox vanishes.
Laptop gets a lease/IP 192.168.43.10 via ethernet cable
ping to 192.168.43.1 gives ~1msec
SSH (Putty) still drops a Timeout Error
giving up after 20+ minutes and numerous trials to SSH 192.168.43.1

So, where to go now from here? I'd be grateful for any hints and am more than willig to provide further info

Kindest Regards

**Comment by radio24** [comment]
Thank you for bringing up this old, unresolved issue!

We still have the same restrictions: when starting up the first time, TorBox assumes that the internet is connected to `eth0` and the clients are coming from `wlan0` or `eth1` (with a USB ethernet adapter). The experiences building the [TorBox mini version](https://www.torbox.ch/?page_id=3544) showed that an automatic detection routine during the start-up of the TorBox is not what we want. It will produce more problems than solutions. However, we should implement a way for the network configuration to be done before we cut the AP connection. An initial connection with the TorBox's AP would still be necessary, but no external screen or keyboard.

After testing the fundamental configurations and scripts, I will work on such a solution. For this test, I did the following:
- Create an SD card with TorBox v0.5.4 on it.
- Connect the client (a MacBook pro) with an USB-C ethernet adapter via an Ethernet cable directly with the Ethernet connector on the Raspberry Pi 5. I also connected the Raspberry Pi 5 to an external screen and a keyboard for this test.
- Start up the Raspberry Pi 5, answer the questions during the [First Start-up Dialogue](https://www.torbox.ch/?page_id=2637), but skip the Internet selection with ESC for now.
- In the end, the First Start-up Dialogue appeared a second time, which I quit. It shouldn't do that, but I didn't find the reason.
- In the [Danger Zone](https://www.torbox.ch/?page_id=3445), I **disabled** the "AP on wlan1 failsafe" (entry 4).
- Select the Internet source from wlan0 (entry 7) in the main menu. Currently, this step has to be done via the external keyboard on the Raspberry Pi itself rather than through SSH because the connection will be cut before the configuration concludes. **That's why you got the IP 192.168.43.10 for your Windows client but couldn't connect with SSH.**
- On the client, ensure that the Ethernet interface supports DHCP and that all other network connections are disabled. The Ethernet interface should get the IP 192.168.43.10. TorBox will get 192.168.43.1.
- With an SSH client, connect to 192.168.43.1 with username `torbox` and password `CHANGE-IT`.
- Currently, the configuration will not work after a reboot. The reason is that `iptables` fails to be persistent.

**What are the next steps?**
- [ ] To ensure that `iptables` is persistent if the "AP on wlan1 failsafe" is disabled.
- [ ] To find a way to change the configuration via the default wlan connection.
- [ ] Testing the implementation on the Raspberry Pi 5
- [ ] Final testing on a Raspberry Pi 3B

What we are not going to change
- An automatic detection routine configuring the network without user interaction
- A separate image file with a specific network configuration

**Comment by airgap0** [comment]
Just what did work for me reliably:

New Balena-etched tb-image > 16 GB Sandisk
Raspberry 3B Plus Version 1.3
2nd WLAN Dongle on USB wlan1
ETH0 > Laptop
Cold start raspi
Found Torbox AP on WIFI
conn. Laptop to Raspi on WIFI
SSH to torbox@192.168.42.1
new ssh-ed host key found > accept
drop and reconnect ssh
new ssh-ed25519 host key found > accept
StartUp Dialogue:
	Yes(Continue)
	No (Change of hostname)
	No (Countermeasures)
Where does the Internet come from?
	wlan1
Continue ? > yes
Open Access > yes
Connect to AP at home 
Connect success - Q to quit
TACA > Yes
Check System time ok > Y
Activate bridges?  No
Bootstrap TOR 100% > Q

ESC to command prompt
sudo iptables -L > iplog.txt
ifconfig > ifc.log
	wlan0 192.168.42.1
	eth0 192.168.43.1
	wlan1 > IP of home AP
./menu > back to normal UI

open another SSH to 192.168.43.1 (LAN)

both SSH Connections are functional checked by Option 1 "Tor statistics
Wireless SSH: ESC to command prompt and exit SSH
LAN SSH still functional
close WLAN on Laptop disable WLAN on Laptop

SSH via LAN:
[Where ist the Internet?]
set it to wlan0
continue? > YES
Open Access > yes
Connect to AP at home (IP in green: 192.168.42.1 !!!)
Connect success - Q to quit

ESC - ESC (!) to command prompt
sudo iptables -L >> iplog.txt
ifconfig >> ifc.log
	wlan0 192.168.42.1
	eth0 192.168.43.1
	wlan1 192.168.42.1 (sic!)

./menu

Remove WIFI dongle at wlan1


Another go with the wireless Manager:

[Where ist the Internet?]
set it to wlan0
continue? > YES
Open Access > yes
Connect to AP at home (IP in green now: IP of home AP)
connect to TOR stuck at 95%
q

retry with wireless Manager and success after a very Long stay (some minutes) at stage 95% bootstrapped

Reboot...Torbox can be reached over eth0

Power off … Torbox can be ssh'ed over Ethernet

[ifc.log](https://github.com/user-attachments/files/18163272/ifc.log)
[iplog.txt](https://github.com/user-attachments/files/18163275/iplog.txt)

**Comment by radio24** [comment]
That's not a surprise - it is built to work that way.
However, I want that an extra WIFI dongle at wlan1 is not necessary.

The steps should follow the following logic:
- Start up a new TorBox installation
- Connect your client with the TorBox AP running on the onboard chip (wlan0) of the Raspberry Pi
- Select that the Internet source is the onboard chip (wlan0) which will cut the connection between the client and the TorBox.
- Connect the client with the Ethernet cable.
- Start-up again the TorBox, which is now accessible via the Ethernet cable
- Select again that the Internet source is the onboard chip (wlan0).

**Comment by radio24** [comment]
Starting point: the TorBox is updated with the latest changes (including copying the updated `/home/torbox/torbox/rc.local` to `/etc/rc.local`), up and running. My only connection from the client to the TorBox is through TorBox's AP running on the onboard WiFi chip (`wlan0`) - according to the default configuration. At this point, It doesn't matter if the TorBox is connected to the Internet.

Next, I connect my client with an Ethernet cable with the Ethernet connector from the Raspberry Pi 5 (`eth0`). In the main menu (which is already updated with the latest changes), I choose entry 7. A new information screen is displayed informing that changing the the connection from wlan0 to eth0 will most likely result in a disconnection and that, in this case, TorBox has to be restarted with the Ethernet cable from the client connected.

After TorBox's manual restart and with the Ethernet cable connected, I can access TorBox's main menu via SSH on `192.168.43.1`. In the main menu, I choose entry 7 again to get an Internet connection via the onboard chip (wlan0). The new information screen pops up again, but it doesn't matter what I choose now.

If I want to go back, with TorBox's AP running on the onboard chip (`wlan0`) and the Internet coming from an Ethernet cable connection (`eth0`), I choose in the main menu entry 5. Again, it's not surprising that my client ended up disconnected from the TorBox. Again, I do a manual restart, connect again with TorBox's AP, access TorBox's main menu via SSH on `192.168.42.1` and choose entry 5 in the main menu to finish the configuration, which leads to Internet access via the Ethernet cable (`eth0`).

There are still some tests to do, but it seems stable. With some additional commands, I also decreased the likelihood of a lock-out situation again in case of misconfiguration. Unfortunately, my new [Netgear AXE3000 Nighthawk WiFi 6 USB adapter](https://www.torbox.ch/?page_id=3640) suddenly stopped working, but I don't think that has to do with the changed code.

**Comment by radio24** [comment]
Ok... the changes gave me more work than I expected. Nevertheless, the invested time was worth it because I could improve the network configuration part used for changing the Internet source should be better than before. The failsafe switch is still in place, but some additional failsafes are integrated. For example, if someone disables the "AP on wlan1 failsafe" and something gets wrong during the network reconfiguration, after the restart, the requested configuration should be ready, and a second time running the same main menu entry should only do the last part of the configuration, the connection to the Internet.

Let's do a new test with the changed files (@airgap0: it would be cool if you could reproduce it):
- Create an SD card with TorBox v0.5.4 on it.
- Start up the Raspberry Pi 5, answer the questions during the [First Start-up Dialogue](https://www.torbox.ch/?page_id=2637) and select the onboard chip (`wlan1`) as an Internet source.
- Go into the [Update and Maintenance menu](https://www.torbox.ch/?page_id=1410) and select entry 5 to update the TorBox menu.
- Leave the TorBox menu by pressing ESC. On the terminal, run the following commands:
```
sudo cp etc/rc.local /etc/rc.local
sudo cp etc/tor/torrc /etc/tor/torrc 
```
- Disabled the "AP on wlan1 failsafe" In the [Danger Zone](https://www.torbox.ch/?page_id=3445) (entry 4) to make the changes permanent.
- Connect the client to the TorBox using the Ethernet cable.
- The client probably already got an IP via DHCP (`192.168.43.10`). If this is the case, SSH into TorBox by using `192.168.43.1` with username `torbox` and password `CHANGE-IT.` Whether you are still connected via `wlan0` or already via `eth0`, you must run entry 7 in the main menu to change the Internet source to `wlan0`. 
- If you do it on `wlan0`, you must ensure that if the client drops the WiFi connection, you immediately reconnect to it so the scripts can continue. If something goes wrong and you are locked out, restart TorBox using the attached Ethernet cable.
- I did it through the attached Ethernet cable but had to run entry 7 in the main menu twice. After that, it worked as expected without a WiFi connection.

I will perform some more tests the next day. If everything goes as planned, I will update the image files soon.

**Comment by airgap0** [comment]
Ok, will do so on a Pi3, because no Pi5 at hand and my other Pi4 is busy doing my website, so it will be a litte tricky to have the Pi4 pause the website. Unfortunately I am busy with family until 12/26

 

Von: TorBox ***@***.*** 
Gesendet: Samstag, 21. Dezember 2024 23:29
An: radio24/TorBox ***@***.***>
Cc: airgap0 ***@***.***>; Mention ***@***.***>
Betreff: Re: [radio24/TorBox] Client > eth0 > TorBox > wlan0 > Internet | Please advise how to ssh to TorBox over ethernet from the first start (Issue #101)

 

Ok... the changes gave me more work than I expected. Nevertheless, the invested time was worth it because I could improve the network configuration part used for changing the Internet source should be better than before. The failsafe switch is still in place, but some additional failsafes are integrated. For example, if someone disables the "AP on wlan1 failsafe" and something gets wrong during the network reconfiguration, after the restart, the requested configuration should be ready, and a second time running the same main menu entry should only do the last part of the configuration, the connection to the Internet.

Let's do a new test with the changed files ***@***.*** <https://github.com/airgap0> : it would be cool if you could reproduce it):

*	Create an SD card with TorBox v0.5.4 on it.
*	Start up the Raspberry Pi 5, answer the questions during the First Start-up Dialogue <https://www.torbox.ch/?page_id=2637>  and select the onboard chip (wlan1) as an Internet source.
*	Go into the Update and Maintenance menu <https://www.torbox.ch/?page_id=1410>  and select entry 5 to update the TorBox menu.
*	Leave the TorBox menu by pressing ESC. On the terminal, run the following commands:

sudo cp etc/rc.local /etc/rc.local
sudo cp etc/tor/torrc /etc/tor/torrc 

*	Disabled the "AP on wlan1 failsafe" In the Danger Zone <https://www.torbox.ch/?page_id=3445>  (entry 4) to make the changes permanent.
*	Connect the client to the TorBox using the Ethernet cable.
*	The client probably already got an IP via DHCP (192.168.43.10). If this is the case, SSH into TorBox by using 192.168.43.1 with username torbox and password CHANGE-IT. Whether you are still connected via wlan0 or already via eth0, you must run entry 7 in the main menu to change the Internet source to wlan0.
*	If you do it on wlan0, you must ensure that if the client drops the WiFi connection, you immediately reconnect to it so the scripts can continue. If something goes wrong and you are locked out, restart TorBox using the attached Ethernet cable.
*	I did it through the attached Ethernet cable but had to run entry 7 in the main menu twice. After that, it worked as expected without a WiFi connection.

I will perform some more tests the next day. If everything goes as planned, I will update the image files soon.

**Comment by radio24** [comment]
I finished my tests on a Raspberry Pi 3B+ according to my descriptions [here](https://github.com/radio24/TorBox/issues/101#issuecomment-2558256736). 
It is running as expected, and I updated the image file (dated 30.12.2024). 
I don't see any reason to keep the issue open, mainly because I have to handle other issues and requests.
