### ISSUE TITLE
No internet 

### ISSUE THREAD

**Issue by Daglas69** [radio24/TorBox#16]
Hello. I've been trying to install TorBox for almost one day and i can't figure out why it is not working.

Basically, the hotspot appears in my networks available, TOR is working according to TorBox menu, but when I am connecting to the wifi I dont have internet.
Moreover, there is an issue when booting : [FAILED] Failed to start dhcpcd on all interfaces

And during the first boot I got many issues like this (for hostapd, dnsmasq, isc-dhcpcd,...)

Which version of the Raspberry Pi and TorBox do you use? 
Raspberry PI 4 and TorBox 0.3.0

Could you connect the TorBox WiFi (for example, “TorBox030”)? If no: Which clients did you try?
I can but I dont have internet access

Could you access the TorBox with an SSH client, and did you see the main menu? If no: Which SSH clients did you try?
I can not access to TorBox with using SSH (I used putty)

How did you connect your TorBox with the Internet? Did you already try with a wireless USB adapter?
I tried with ethernet, wireless with my mobile hotspot, and using usb network sharing with my mobile too

What kind of power supply do you use?
The official one

In which country did you try to connect TorBox with the Internet.
France

What else did you already try (which menu entries), and which error messages did you see?
I tried all options possible. I dont have error messages but I can not access to internet when connecting to the router from another device.

Thank you in advance for helping me.

**Comment by radio24** [comment]
Daglas also contacted us by email and thanks to the detailed information (see [the corresponding entry in the FAQ](https://www.torbox.ch/?page_id=112#i-cant-get-torbox-to-work-and-need-more-detailed-help-what-should-i-do)) we were able to help him. Below is a summary of the various problems Daglas faced so that other users can benefit from it.

**dhcpcd failure? Strange messages during the first boot?**
This failure does not affect TorBox because it doesn't use dhcpcd. To avoid this failure during the boot up of TorBox, we will entirely disable dhcpcd in the next TorBox version. Error messages during the first boot are nothing unusual. Don't forget: the system on the SD card automatically expands over the entire free partition during the first boot.

**Possible IP address conflict between the Internet router and TorBox?**
His IP router provided TorBox's ethernet interface this IP address: 192.168.1.58, which is defined as "[private network](https://en.wikipedia.org/wiki/Private_network)". TorBox is using the same private network range (192.168.42.1 and 192.168.42.3), which in very rare cases may lead to problems (I didn't have such a case until yet). At first, we thought that this might be the source of the problem. However, the connection problems occurred whenever the connection via WLAN was attempted. Changing the IP on the Internet router side did not help.

**Necessity of a WLAN USB adapter! <-- This was the problem**
Finally, we figured out that Daglas tried to establish an **Internet<->wlan-TorBox-wlan<->Client** connection with Raspberry Pi's onboard wlan chip. He is not the only one who tried that, but that's not possible! For such a configuration, an adapter is needed because neither the Raspberry Pi onboard wlan chip nor the USB adapter can access the Internet and the client simultaneously. I have already tightened the description of the website in this regard and included this point into the FAQ.
