### ISSUE TITLE
Capitve portals

### ISSUE THREAD

**Issue by GHLover** [radio24/TorBox#2]
Wonderful project! Can you add to the FAQ how getting around captive portals work?

I assume it requires logging into the PI somehow and temporarily disabling Tor and the various protections. I am interested to know in the exact process.

**Comment by radio24** [comment]
Hello GHLover,
thanks for your feedback. Usually, getting around a captive portal is an easy process. In order to do that, you have to do following steps:
- Access your TorBox (192.168.42.1) with an SSH-client 
- In the appearing TorBox menu, choose the preferred connection setup (with a Captive Portal, usually it is "Wireless-internet to wireless-clients"
- Now you can choose between "Captive Portal" and "Open Access" (see image below)
- The rest of the procedure is guided through a menu dialog and should be self-explanatory.

<img width="680" alt="Captive_Portal_on_TorBox v 0 2 3" src="https://user-images.githubusercontent.com/46644350/55666780-d4f70880-5853-11e9-8538-d599b3cd244f.png">

Please tell me exactly, where you're having trouble, so that I can help you, improve the menu dialogue and as you mentioned, add an entry to the FAQ.
