### ISSUE TITLE
Raspberry Pi 3 - repo

### ISSUE THREAD

**Issue by TemhAAhmeT** [radio24/TorBox#30]
deb https://deb.torproject.org/torproject.org buster main

torproject doesnt support armhf

N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://deb.torproject.org/torproject.org buster InRelease' doesn't support architecture 'armhf'

also keyring is expired for this repo
new key:
curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -

**Comment by radio24** [comment]
Hello TemhAAhmeT
Thank you for that feedback. Unfortunately, because of my workload, I cannot fix this issue right away. I expect to find time to provide an update at the beginning of March.

**Comment by radio24** [comment]
Hello TemhAAhmeT
I looked into it. Yes, this error message is appearing if in the Update and Reset submenu entry 1 is used. For that reason, we have in the same submenu entry 3, which installed the newest tor version from the source package. Armhf support is not necessary, because the binaries will be compiled on the Raspberry Pi.
The key added during the update should work just fine. 
To be sure, I will try it tomorrow again.

**Comment by radio24** [comment]
Hello TemhAAhmeT
Today, on the base of TorBox v. 0.3.2, first, I updated the base system (in the Update and Reset submenu entry 1). Afterwards, I updated Tor to version 0.4.4.6 without any problem (in the Update and Reset submenu entry 3).

**Comment by radio24** [comment]
For more information see also here: [https://www.torbox.ch/?p=1949](https://www.torbox.ch/?p=1949)
